### PR TITLE
finish refactor of downloadURLs to downloadURLQueue

### LINKED ISSUE #110: Downloading XML files from EuropePMC is broken
As the title suggests this is now broken. Something changed when the CrossRef code was merged in download.js which broke things

```
Student@N340641206-4C MINGW64 /c/git/contentmine/getpapers (master)
$ bin/getpapers.js -q test -k 1 -x -o troop
info: Searching using eupmc API
info: Found 926130 open access results
info: Limiting to 1 hits
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Saving result metadata
info: Full EUPMC result metadata written to eupmc_results.json
info: Individual EUPMC result metadata records written
info: Extracting fulltext HTML URL list (may not be available for all articles)
info: Fulltext HTML URL list written to eupmc_fulltext_html_urls.txt
warn: Article with pmid "27148617 did not have a PMCID (therefore no XML)
info: Got XML URLs for 99 out of 100 results
info: Downloading fulltext XML files
C:\git\contentmine\getpapers\lib\eupmc.js:250
  urlDl.downloadURLs(urlQueue, eupmc.nextDlTask.bind(eupmc));
        ^

TypeError: urlDl.downloadURLs is not a function
    at EuPmc.downloadFulltextXMLs (C:\git\contentmine\getpapers\lib\eupmc.js:250:9)
    at EuPmc.nextDlTask (C:\git\contentmine\getpapers\lib\eupmc.js:232:5)
    at EuPmc.runDlTasks (C:\git\contentmine\getpapers\lib\eupmc.js:221:9)
    at EuPmc.handleSearchResults (C:\git\contentmine\getpapers\lib\eupmc.js:211:9)
    at EuPmc.completeCallback (C:\git\contentmine\getpapers\lib\eupmc.js:113:11)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (C:\git\contentmine\getpapers\node_modules\restler\lib\restler.js:229:10)
    at C:\git\contentmine\getpapers\node_modules\restler\lib\restler.js:161:20
    at C:\git\contentmine\getpapers\node_modules\restler\lib\restler.js:456:9
```

### PR DESCRIPTION
**Pull request by tarrow**
fixes #110

### CODE REVIEW

**Comment by tarrow** [comment]
This is a super minor change but could you take a look and merge it and cut a new release? Without out it people are unable to download xmls from EuPMC

**Comment by blahah** [comment]
Looks good @tarrow - I haven't checked but do these changes also need to be applied to arxiv and ieee?

**Comment by tarrow** [comment]
This patch fixes arxiv as well and ieee didn't need fixing because it doesn't do paper downloads :)

**Comment by blahah** [comment]
aha!

**Pull request merged**
