### PR TITLE
Added option to limit number of hits

### PR DESCRIPTION
**Pull request by tarrow**
This is a patch to limit the number of hits with -k or --limit. It also fixes a possible bug #74

### CODE REVIEW

**Comment by Blahah** [comment]
cc #65

**Comment by Blahah** [comment]
Great! Please make sure it applies to all the APIs.

**Comment by tarrow** [comment]
Whoops, I sort of over looked this. Should I be making an arxiv patch on master or on the arxiv update branch?

**Comment by Blahah** [comment]
I've now merged the arxiv branch into master, so you can fetch the changes and work directly in this PR

**Comment by tarrow** [comment]
Great; I'll get right on that!

**Comment by tarrow** [comment]
you'll notice in my PR I changed the pageSize param we send to EuropePMC to 100. the default is 25 but it can be as many as 1000. Do you have any thoughts as to what we should set it to? A larger number means fewer requests but it takes EuropePMC longer to respond. At 1000 we can hit the timeout. It also means the progress bar has much less granularity.

This is in this pull request because obviously we need to know the page size to page it.

**Comment by tarrow** [comment]
If you could have a look at this for me @Blahah that would be great. I think it is ok; I'm always keen to get back any criticism you might have about style or logic though.

It should address all apis and enable -k to limit the number of papers.

It also closes #74.

**Comment by petermr** [comment]
This would be super valuable. In demos it's useful to limit demo to (say) 200 hits.

**Comment by tarrow** [comment]
Subject to code-review by @Blahah this code should now all be ready to go.

**Comment by Blahah** [comment]
@tarrow sorry it took me a while to get to this.

RE the page size for eupmc - 100 is fine for now. I set the ArXiv one by experimenting with a range of values and choosing the largest one that never timed out in a large number of test runs. But it's probably internet connection speed dependent - we may have to revisit later.

Code all looks good - great job!

**Pull request merged**
